# Basic options
title: Computational Thinking
short_name: Computational Thinking
developers: [Eilis Hannon, Jessica Shields]
description: Introduction to some fundamental principles that are the basis of writing computer code in any language.
n_sessions: 2
prereq: NA
url: https://uniexeterrse.github.io/computational-thinking

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
